default:
  image: archlinux:base-devel
  before_script:
  - pacman -Syu --noconfirm rustup
  - rustup toolchain install nightly

include:
- project: "renovate-bot/renovate-runner"
  file: "/templates/renovate.gitlab-ci.yml"

stages:
- sanity
- build
- test
- renovate

clippy:
  stage: sanity
  script:
  - rustup component add clippy
  - cargo clippy

rustfmt:
  stage: sanity
  script:
  - rustup component add rustfmt
  - cargo fmt --check

build:
  stage: build
  script:
  - cargo build

unit-test:
  stage: test
  script:
  - cargo test

renovate:
  before_script: []
  stage: renovate
  rules:
  # triggered by scheduler
  - if: $CI_PIPELINE_SOURCE == "schedule"
  # triggered by web ui
  - if: $CI_PIPELINE_SOURCE == "web"
