hard_tabs = true
imports_layout = 'Vertical'
imports_granularity = 'Preserve'
max_width = 120
comment_width = 120
match_block_trailing_comma = true
tab_spaces = 4
struct_lit_single_line = true
indent_style = "Block"
